In [125]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sp

In [126]:
metric = np.array([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
identity = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

print("Metric matrix:")
print(metric)
print(" ")
print("Identity matrix: ")
print(identity)

Metric matrix:
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]
 
Identity matrix: 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [170]:
#Generators of vectorial representation
i = 1j

#Create 4-tensor
J = np.zeros(shape = (4, 4, 4, 4))

#Initialize the generators
for mu in range(4):
    for nu in range(4):
        for alpha in range(4):
            for beta in range(4):
                J[mu, nu, alpha, beta] = (metric[mu, alpha] * identity[nu, beta] - metric[nu, alpha] * identity[mu, beta])
            

In [171]:
from itertools import permutations

#Levi-civita symbol initialization
epsilon = np.zeros(shape = (3, 3, 3))

non_zero_indices = [0, 1, 2]
permutation_non_zero = permutations(non_zero_indices)
permutation_non_zero = list(permutation_non_zero)

#Ordering the permutation list in even (+1) and odd (-1)
permutation_non_zero[1], permutation_non_zero[3] = permutation_non_zero[3], permutation_non_zero[1]
permutation_non_zero[2], permutation_non_zero[4] = permutation_non_zero[4], permutation_non_zero[2]

#Initialization of non zero components:
for p in range(len(permutation_non_zero)): 
    if(p < 3):
        epsilon[permutation_non_zero[p]] = 1
    else:
        epsilon[permutation_non_zero[p]] = -1
        
#The other components are already 0 by def

In [172]:
#Angular Momentum
L = np.zeros(shape = (3, 4, 4))

for j in range(3):
    for alpha in range(4):
        for beta in range(4):
            
            for k in range(3):
                for t in range(3):
                    L[j, alpha, beta] += 0.5*epsilon[j, k, t]*J[k+1, t+1, alpha, beta]
                    
                    
#Boosts
K = np.zeros(shape = (3, 4, 4))
for j in range(3):
    for alpha in range(4):
        for beta in range(4):
            
            K[j, alpha, beta] = J[0, j+1, alpha, beta] 
            
#Make entries imaginary numbers
L = i*L
K = i*K
                    

In [180]:
#Define ladder operators
J_p = complex(0.5) * (L + i*K)
J_m = complex(0.5) * (L - i*K)

print("J+ Matrices:")
print(J_p)

J+ Matrices:
[[[ 0. +0.j  -0.5+0.j   0. +0.j   0. +0.j ]
  [-0.5+0.j   0. +0.j   0. +0.j   0. +0.j ]
  [ 0. +0.j   0. +0.j   0. +0.j   0. -0.5j]
  [ 0. +0.j   0. +0.j   0. +0.5j  0. +0.j ]]

 [[ 0. +0.j   0. +0.j  -0.5+0.j   0. +0.j ]
  [ 0. +0.j   0. +0.j   0. +0.j   0. +0.5j]
  [-0.5+0.j   0. +0.j   0. +0.j   0. +0.j ]
  [ 0. +0.j   0. -0.5j  0. +0.j   0. +0.j ]]

 [[ 0. +0.j   0. +0.j   0. +0.j  -0.5+0.j ]
  [ 0. +0.j   0. +0.j   0. -0.5j  0. +0.j ]
  [ 0. +0.j   0. +0.5j  0. +0.j   0. +0.j ]
  [-0.5+0.j   0. +0.j   0. +0.j   0. +0.j ]]]


In [179]:
print(" ")
print("J- Matrices:")
print(J_m)

 
J- Matrices:
[[[0. +0.j  0.5+0.j  0. +0.j  0. +0.j ]
  [0.5+0.j  0. +0.j  0. +0.j  0. +0.j ]
  [0. +0.j  0. +0.j  0. +0.j  0. -0.5j]
  [0. +0.j  0. +0.j  0. +0.5j 0. +0.j ]]

 [[0. +0.j  0. +0.j  0.5+0.j  0. +0.j ]
  [0. +0.j  0. +0.j  0. +0.j  0. +0.5j]
  [0.5+0.j  0. +0.j  0. +0.j  0. +0.j ]
  [0. +0.j  0. -0.5j 0. +0.j  0. +0.j ]]

 [[0. +0.j  0. +0.j  0. +0.j  0.5+0.j ]
  [0. +0.j  0. +0.j  0. -0.5j 0. +0.j ]
  [0. +0.j  0. +0.5j 0. +0.j  0. +0.j ]
  [0.5+0.j  0. +0.j  0. +0.j  0. +0.j ]]]


In [196]:
#Casimir Operators
J_p_squared = np.zeros(shape = (4, 4))

for m in J_p:
    J_p_squared = np.dot(m, m) + J_p_squared
    
J_m_squared = np.zeros(shape = (4, 4))

for m in J_m:
    J_m_squared = np.dot(m, m) + J_m_squared
    
print("Casimir Jp: ")
print(J_p_squared)

print(" ")
print("Casimir Jm: ")
print(J_m_squared)



Casimir Jp: 
[[0.75+0.j 0.  +0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.75+0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.75+0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.  +0.j 0.75+0.j]]
 
Casimir Jm: 
[[0.75+0.j 0.  +0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.75+0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.75+0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.  +0.j 0.75+0.j]]
